query getGame {
  game(id: "636aca4b8f383a197d633144") {
    id
    players {
      id
      name
      resources {
        brick
        wood
        sheep
        grain
        rock
      }
    }
  }
}
