import { ApolloProvider } from "@apollo/client";
import { AppShell } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import Dashboard from "../components/organisms/Dashboard";
import Header from "../components/organisms/Header";
import client from "../utils/apollo";

const Home: NextPage = () => {
  return (
    <ApolloProvider client={client}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppShell header={<Header />}>
          <Dashboard />
        </AppShell>
      </main>
    </ApolloProvider>
  );
};

export default Home;
