import type { NextPage } from "next";
import Head from "next/head";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";
import { AppShell, Navbar } from "@mantine/core";
import Dashboard from "../components/organisms/Dashboard";
import Header from "../components/organisms/Header";

const client = new ApolloClient({
  uri: "http://localhost:3030/graphql",
  cache: new InMemoryCache(),
});

const Home: NextPage = () => {
  return (
    <ApolloProvider client={client}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppShell header={<Header />}>
          <Dashboard />
        </AppShell>
      </main>
    </ApolloProvider>
  );
};

export default Home;
